program: train_mnist.py
method: grid
parameters:
  lr_schedule:
    values: [ step, cyclic ]
  epoch_total:
    values: [ 2, ]
metric:
  goal: maximize
  name: test-result/accuracy
project: my-mnist-test-project
name: MNIST-Sweep-Test
description: test sweep demo
